/* ============================================================
   LANGUES — tous les textes affichés vivent ici (en / fr).
   Ils sont résolus AU RENDU : changer de langue dans les
   paramètres met toute l'interface à jour, même en pleine main.
   Les valeurs sont soit des chaînes, soit des fonctions
   d'interpolation, soit des tableaux (mots tirés au hasard).
   Les nombres/monnaies arrivent DÉJÀ formatés (voir cash()).
   ============================================================ */
const LANGS=[{id:'en',label:'ENGLISH'},{id:'fr',label:'FRANÇAIS'}];
const STR={
en:{
/* --- chrome de jeu --- */
'ui.turnsLeft':'TURNS<br>LEFT','ui.hand':(a,b)=>'hand '+a+'/'+b,
'ui.bet':'BET','ui.mult':'MULT','ui.gain':'CASH','ui.potLbl':'POT',
'ui.dealer':'Dealer','ui.you':'You','ui.peek':'PEEK','ui.peekTitle':'Read the next card in the shoe',
'ui.pause':'Pause','ui.lives':'Lives (second chances)','ui.streak':'STREAK',
'ui.lvl':(l,m)=>'· LV '+l+' ×'+m,'ui.relics':'relics',
'ui.next':c=>'NEXT: '+c,'ui.bustRisk':p=>'BUST RISK: '+p+'%',
/* --- menu principal --- */
'menu.sub':'Pick your game mode. Each one has <b>its own Hideout</b> and <b>reputation</b>.',
'menu.circuit':'THE CIRCUIT','menu.circuitSub':n=>n+' tables · one ending · relics & tarots',
'menu.endless':'ENDLESS','menu.endlessSub':'pure blackjack · climb the tiers',
'menu.recTables':d=>'best '+d+' table'+(d===1?'':'s'),'menu.recTier':p=>'best tier '+p,
/* --- La Planque --- */
'planque.title':'THE HIDEOUT',
'planque.subCircuit':'Spend your <b>reputation</b> on permanent perks, then head out for a new <b>circuit</b>.',
'planque.subInf':'Upgrade your <b>pot</b> with your <b>reputation</b>, then dive back in.',
'planque.modeCircuit':'THE CIRCUIT','planque.modeInf':'∞ ENDLESS',
'planque.rep':'reputation','planque.best':'BEST',
'planque.tables':d=>d+' table'+(d===1?'':'s'),'planque.tierN':p=>'tier '+p,
'planque.upgrades':'UPGRADES','planque.upgradesSub':'permanent perks',
'planque.allMax':'all maxed','planque.avail':n=>n+' available',
'planque.leadCircuit':'Spend your <b>reputation</b> on permanent perks.',
'planque.leadInf':'Strengthen your <b>pot</b> with your <b>reputation</b>.',
'planque.back':'CARD BACK','planque.backSub':(i,n)=>'design '+i+' / '+n,
'planque.backLead':'Pick the artwork on the back of your cards.',
'planque.seeAll':'see all ▸','planque.menu':'← MENU','planque.start':'START',
'planque.startInf':'endless · pure blackjack','planque.startResume':n=>'resume · table '+n,
'planque.startCircuit':n=>'the circuit · '+n+' tables',
'planque.zone2':'ZONE 2','planque.zone2Sub':'shortcut',
'planque.resumeTable':'RESUME AT','planque.resumeTier':'RESUME AT',
'planque.tierLabel':n=>'Tier '+n,'planque.tableLabel':n=>'Table '+n,
'planque.max':'MAX','planque.prevBack':'Previous back','planque.nextBack':'Next back',
'planque.restartTitle':'Restart this mode (loses the mode’s reputation)','planque.rulesTitle':'Game rules',
/* --- paramètres --- */
'set.title':'SETTINGS','set.open':'⚙ SETTINGS','set.lang':'LANGUAGE','set.close':'CLOSE','set.btnTitle':'Settings',
/* --- publicité (bouchon de démo) --- */
'ad.tag':'AD','ad.interTag':'INTERSTITIAL','ad.rewardedTag':'REWARDED AD',
'ad.yourAd':'YOUR AD HERE','ad.format':'placeholder · 320×480','ad.install':'INSTALL',
'ad.demoTag':'DEMO — no ad network connected','ad.demoClick':'Demo ad — nothing to click',
'ad.skipIn':n=>'Skip in '+n+' s','ad.continue':'CONTINUE',
'ad.rewardIn':n=>'Reward in '+n+' s','ad.rewardGot':'REWARD UNLOCKED','ad.claim':'CLAIM',
'ad.aborted':'Reward missed','ad.demoReward':'Demo reward',
'ad.retryBtn':'▶ SECOND CHANCE','ad.retrySub':n=>'watch an ad · '+n+' left',
'ad.retryReward':'Replay this table','ad.retryAborted':'Ad skipped — no second chance',
'ad.repBtn':'▶ DOUBLE YOUR REPUTATION','ad.repSub':r=>'+'+r+' on top','ad.repReward':r=>'+'+r+' reputation',
'ad.rerollBtn':'▶ FREE','ad.rerollReward':'One free shop reroll',
'ad.boonBtn':'▶ REROLL THE PERKS','ad.boonSub':'3 new options','ad.boonReward':'3 new perks',
/* --- paramètres : pub --- */
'set.ads':'ADS (DEMO)','set.adTestI':'TEST INTERSTITIAL','set.adTestR':'TEST REWARDED',
'set.adFree':'REMOVE ADS','set.adCaps':'IGNORE CAPS','set.on':'ON','set.off':'OFF',
'set.adsNote':'Demo only: no ad network is connected. “Remove ads” simulates the IAP (keeps rewarded ads). “Ignore caps” fires every interstitial so you can preview them — off, the real rules apply: 1 ad max every 3 tables and never less than 2 min apart.',

/* --- règles --- */
'rules.title':'RULES','rules.close':'CLOSE',
'rules.goal':'<span class="rt">GOAL</span>Beat the dealer on every hand without going over <span class="k">21</span>. Face cards are worth 10, an Ace is 1 or 11.',
'rules.table':'<span class="rt">THE TABLE</span>Play <span class="k">every required hand</span>, bet within the <span class="k">limits</span> (fixed min–max), and reach the <span class="k">cash goal</span> before the last hand. Below the goal = table lost.',
'rules.moves':'<span class="rt">YOUR MOVES</span><span class="k">HIT</span> for a card, <span class="k">STAND</span> on your hand, or <span class="k">FORCE YOUR LUCK</span> (2 cards, keep the best · 1×/table).',
'rules.stars':'<span class="rt"><i class="pxstar"></i> STARS</span>Every table awards them based on your result: <span class="k">goal</span> · <span class="k">comfort</span> · <span class="k">mastery</span>. The more you take, the higher your <span class="k">reputation</span> climbs.',
'rules.streak':'<span class="rt">STREAK</span>Your <span class="k">luck</span> bar rises with every win (<span class="k">gutsy play = +2</span>) and unlocks stronger and stronger <span class="k">multipliers</span>. Losing a hand <span class="d">wipes it out</span>.',
'rules.combos':'<span class="rt">COMBOS</span>The real game: <span class="k">build</span> your hands, don’t just beat the dealer.<br><span class="k">PERFECT 21 ×3</span> · <span class="k">CHARLIE</span> (5 cards) ×2 · <span class="k">FLUSH</span> (3+ same suit) ×2 · <span class="k">STRAIGHT</span> (3+ ranks in a row) ×2 · BLACKJACK ×1.5 · PAIR OF 7s ×1.5 · RAINBOW (4 suits) ×1.5.<br>The pills on the felt show what you already have and what’s within reach.',
'rules.bonus':'<span class="rt">SMALL BONUSES</span>Situational nudges to the multiplier: <span class="k">COURT</span> (2+ face cards) ×1.5 · <span class="k">LOWBALL</span> (win with ≤15) ×1.5 · <span class="k">BY ONE</span> (beat the dealer by a single point) ×1.5 · <span class="k">CLUTCH</span> (last hand) ×1.5 · <span class="k">COMEBACK</span> (started ≤11, finished ≥17) ×1.3.',
'rules.contracts':'<span class="rt"><i class="pxi pxi-scroll"></i> CONTRACTS</span>Every table offers an <span class="k">optional challenge</span> (“win a 5-card hand”…) worth <span class="k">bonus ★</span>. Done or not, the table carries on as usual.',
'rules.circuit':'<span class="rt">THE CIRCUIT</span><span class="k">24 tables · 8 zones · a boss every 3 levels</span>. After a boss: <span class="k">cash in</span> your reputation at the Hideout, or <span class="d">push on</span> for more. Reach <span class="k">zone 2</span> twice to unlock the <span class="k">shortcut</span>.',
'rules.hideout':'<span class="rt">THE HIDEOUT</span>Spend your <span class="k">reputation <i class="pxstar"></i></span> on permanent perks (relics, tarots, editions) before heading out again.',
'rules.endless':'<span class="rt">ENDLESS</span>No goal: grow your pot for as long as you can bet. Every <span class="k">tier</span> = a perk of your choice and higher bets · every 5 hands, a <span class="d">special hand</span>. <span class="k">CASH OUT</span> turns your pot into reputation — <span class="d">going bust</span> only keeps the tiers.',
/* --- améliorations / galerie --- */
'upg.title':'UPGRADES','backs.title':'CARD BACK',
/* --- recommencer --- */
'rst.title':'RESTART?','rst.text':'Are you sure you want to <b>restart this mode’s progress</b>?<br>You lose the <b>reputation</b>, the <b>unlocks</b> and the <b>record</b> of this mode only.',
'rst.cancel':'CANCEL','rst.ok':'RESTART',
/* --- pause --- */
'pause.title':'PAUSE','pause.sub':'The game is on hold.','pause.resume':'RESUME',
'pause.cash':'CASH OUT','pause.cashSub':'turns your pot into reputation',
'pause.rules':'RULES','pause.menu':'BACK TO MENU','pause.menuSub':'quit the run · you cash in your reputation',
/* --- palier (infini) --- */
'pal.title':'TIER','pal.sub':'Pick a <b>perk</b> for what comes next.',
'pal.cash':r=>'CASH OUT '+r,'pal.cashSub':'stop here · tier bonus +20 %',
/* --- boutique --- */
'shop.title':'TABLE CLEARED','shop.titleBoss':'BOSS DOWN','shop.titleLast':'CASINO CLEANED OUT',
'shop.sub':(d,b,pot,rew)=>'Table <b>'+d+'</b> held · <b>'+b+'</b> in pocket · pot <b>'+pot+'</b> <span style="color:var(--muted)">(+'+rew+')</span>',
'shop.total':'total','shop.reroll':c=>'REROLL ('+c+')',
'shop.cash':'CASH OUT','shop.finish':'FINISH','shop.repSuffix':'rep.',
'shop.next':'NEXT TABLE →','shop.nextInfo':(n,goal,cap,fee)=>n+' · goal '+goal+' · rec. '+cap+fee,
'shop.fee':f=>' · entry fee '+f,
'shop.nextObj':(n,goal,cap)=>'NEXT · <b>'+n+'</b> — goal <b style="color:var(--gold)">'+goal+'</b> · recommended bankroll <b>'+cap+'</b>',
'shop.feeObj':f=>' · entry <b style="color:var(--red)">'+f+'</b>',
'shop.gateFee':f=>'More exclusive room — entry fee '+f+'.',
'shop.gateDone':'You cleared the run. Cash in your reputation.',
'shop.empty':'Nothing to buy here.','shop.tagService':'✚ SERVICE','shop.tagTarot':'TAROT','shop.tagRelic':'◆ RELIC',
'shop.full':'FULL','shop.owned':'OWNED',
/* --- inspection d'un objet --- */
'insp.tarot':'TAROT TOKEN · single use','insp.relic':'RELIC · permanent effect',
'insp.use':'USE','insp.sell':v=>'SELL +'+v,'insp.close':'CLOSE','msg.sold':'SOLD',
/* --- actions --- */
'act.bet':'BET','act.betSub':b=>'bet '+b,'act.betChoose':'pick your bet','act.handSuffix':(h,m)=>' · hand '+h+'/'+m,
'act.hit':'HIT','act.hitSub':'+1 card','act.risk':'RISK IT','act.riskSub':'+bonus if you survive',
'act.stand':'STAND','act.standSub':'keep your hand',
'act.split':'SPLIT','act.splitSub':'pair · two hands',
'act.double':'DOUBLE','act.doubleSub':'bet ×2 · one card only',
'act.force':'FORCE YOUR LUCK','act.forceSub':'keep the best · 1×/table',
'act.forceUsed':'already used this table','act.forceOff':'2 cards 17-20 · keep the best',
/* --- messages de jeu --- */
'msg.notNow':'NOT NOW','msg.notNowSub':'usable during a hand',
'msg.noCards':'NO CARDS','msg.cant':'CAN’T','msg.keep3':'keep ≥3 cards',
'msg.slotsFull':'SLOTS FULL','msg.relicsFull':'RELICS FULL','msg.max':n=>n+' max',
'msg.split':'SPLIT','msg.splitSub':c=>c+' · two hands',
'msg.hand':n=>'HAND '+n,'msg.handSub':'your turn',
'msg.doubled':'DOUBLED','msg.doubledSub':'bet ×2 · one card only',
'msg.forced':'FORCED','msg.kept':c=>'kept '+c,
'msg.insurance':'INSURANCE','msg.insuranceSub':'loss refunded',
'msg.talisman':'TALISMAN','msg.talismanSub':'first loss refunded',
'msg.gutsy':'GUTSY!','msg.gutsySub':n=>'+'+n+' streak',
'msg.entryFee':'ENTRY FEE','msg.boss':'BOSS','msg.miniboss':'MINI-BOSS',
'msg.zone':(n,name)=>'ZONE '+n+(name?' — '+name:''),
'msg.contract':'CONTRACT DONE','msg.income':'INCOME',
'inc.patron':n=>'Patron +'+n,'inc.shark':n=>'Loan Shark +'+n,'inc.tip':n=>'Tip +'+n,'inc.tier':n=>'Tier +'+n,
'msg.endlessStart':'ENDLESS','msg.endlessStartSub':'climb as high as you can',
/* --- multiplicateur / combos --- */
'm.blackjack':'BLACKJACK','m.perfect':'PERFECT 21','m.charlie':'CHARLIE','m.pair7':'PAIR OF 7s',
'm.flush':'FLUSH','m.straight':'STRAIGHT','m.rainbow':'RAINBOW','m.pushing':'PUSHING IT',
'm.streak':l=>'STREAK LV '+l,'m.burner':'BURNER','m.foil':'FOIL','m.holo':'HOLO','m.poly':'POLY',
'm.foilV':n=>'+'+n+' cash','m.ace':'LOADED ACE','m.cool':'COOL HEAD',
'm.court':'COURT','m.lowball':'LOWBALL','m.comeback':'COMEBACK','m.clutch':'CLUTCH','m.byone':'BY ONE',
'm.zonecap':'ZONE CAP','m.golden':'GOLDEN',
'ed.card':n=>n+' CARD','ed.foil':'+ bonus cash','ed.holo':'+1 to the multiplier','ed.poly':'× multiplier',
'cb.to21':n=>'PERFECT 21 ×3 · '+n+' away','cb.charlie':'CHARLIE ×2 · +1 card',
'cb.flush':s=>'FLUSH ×2 · +1 '+s,'cb.rainbow':'RAINBOW ×1.5 · +1 card',
'cb.pair7':'PAIR OF 7s · draw a 7','cb.straight':'STRAIGHT ×2 · possible',
'cb.streak':(l,n)=>'STREAK LV '+l+' in '+n,
/* --- bandeau du haut --- */
'top.mastery':m=>'mastery ≥'+m,'top.betRange':(a,b)=>'bet '+a+'–'+b,
'top.stars':n=>n+' star'+(n>1?'s':''),'top.pot':p=>'pot '+p,
'top.contractDone':'✓ contract done','top.record':v=>'best '+v,
'top.worth':r=>'worth '+r+' if you stop',
'top.metaCircuit':(z,zn,i,n)=>'zone '+z+' · '+zn+' · '+i+'/'+n,
'top.metaInf':(p,a,b)=>'∞ ENDLESS · tier '+p+' · bet '+a+'–'+b,
/* --- mots de résolution --- */
'w.jackpot':['JACKPOT!','MEGA!','BOOM!','ON FIRE!'],
'w.win':['WIN!','YEAH!','BANG!','SMOOTH!','POW!'],
'w.bj':['BLACKJACK!'],'w.push':['PUSH','TIE'],
'w.lose':['MISSED!','DANG!','LOST!','OUCH!'],'w.bust':['BUSTED!','BURNED!','TOO HIGH!'],
'w.betBack':'bet returned',
'sp.win':'WON','sp.push':'PUSH','sp.lose':'LOST','sp.hand':i=>'Hand '+i+': ',
/* --- fin de table / de run --- */
'lost.goal':'GOAL MISSED','lost.goalTxt':m=>'You finish below the table’s cash goal — you were <b style="color:var(--red)">'+m+'</b> short.',
'lost.broke':'BROKE','lost.brokeTxt':'Not enough left to bet the table minimum.',
'lose.info':(n,pot)=>'Table <b>'+n+'</b> · Pot: <b>'+pot+'</b>',
'lose.retry':'SECOND CHANCE','lose.tokens':n=>n+' token'+(n>1?'s':'')+' left',
'lose.giveup':'GIVE UP','lose.giveupSub':r=>'cash in '+r,
'endless.bust':'BANKRUPT','endless.bustTxt':'Nothing left to bet. Your pot ends here.',
'end.cash':'YOU CASH OUT','end.circuitOver':'END OF THE CIRCUIT','end.potGone':'POT WIPED OUT',
'end.cashTxt':'You walk off with the pot before things turn ugly.',
'end.halfTxt':'You still leave with half of your pot.',
'end.infCashTxt':b=>'You turn your pot into reputation'+(b?' — <b style="color:var(--gold)">tier bonus +20 %</b>':'')+'.',
'end.infStopTxt':'Your dive ends here.',
'end.missing':(m,prox)=>'<br>You were <b style="color:var(--red)">'+m+'</b> short of the goal'+(prox?' <span style="color:var(--muted)">— proximity bonus '+prox+'</span>':'')+'.',
'end.infStats':(peak,tier)=>'Best pot: <b style="color:var(--gold)">'+peak+'</b> · Tier reached: <b>'+tier+'</b>',
'end.stats':(d,b)=>'Tables held: <b>'+d+'</b> · Cash: <b>'+b+'</b>',
'end.rep':(g,total)=>'Reputation: <b>'+g+'</b>','end.repTotal':t=>' &nbsp;→&nbsp; total <b>'+t+'</b>',
'end.vault':c=>' <span style="color:var(--muted)">+ vault '+c+'</span>',
'end.newRecord':'NEW RECORD!',
'end.recordInf':(tier,peak)=>'Best: tier '+tier+' · '+peak,
'end.recordCircuit':(d,c)=>'Best: '+d+' table'+(d===1?'':'s')+' · '+c,
'end.won':'HANDS WON','end.bestGain':'BEST WIN','end.bestMult':'BEST MULT','end.back':'BACK TO THE HIDEOUT',
'rec.banner':'★ NEW RECORD ★','obj.reached':'GOAL!','obj.validated':'table cleared',
/* --- tables de la tournée --- */
'tbl.0':'Back Room','tbl.1':'Jittery Table','tbl.2':'The Bouncer','tbl.3':'Damp Cellar',
'tbl.4':'Red Parlour','tbl.5':'The Banker','tbl.6':'Ace Pit','tbl.7':'Cursed Table','tbl.8':'The Reaper',
'tbl.9':'Jade Lounge','tbl.10':'Hushed Table','tbl.11':'The Concierge',
'tbl.12':'Antechamber','tbl.13':'Vault of Secrets','tbl.14':'The Accountant',
'tbl.15':'Backroom Den','tbl.16':'Rat Cellar','tbl.17':'The Gravedigger',
'tbl.18':'Gilded Box','tbl.19':'One-Way Mirror','tbl.20':'The Croupier',
'tbl.21':'Royal Suite','tbl.22':'Masters’ Room','tbl.23':'THE GODFATHER',
'zone.1':'Initiation','zone.2':'The Squeeze','zone.3':'Deep Casino','zone.4':'Red Circle',
'zone.5':'The Vault','zone.6':'The Underbelly','zone.7':'Private Sphere','zone.8':'The Summit',
'rule.nervous':'Streak builds 2× faster','rule.mute':'Silent dealer',
'rule.gros':'The dealer hits up to 18','rule.depart':'Table already hot (+30 %)','rule.sec':'A push counts as a loss',
'rtx.0':'Initiation','rtx.4':'Hushed parlour','rtx.7':'Merciless dealer (18)',
'rtx.boss':r=>'BOSS · '+r,'rtx.bossFinal':'FINAL BOSS · a push counts as a loss','rtx.bossPlain':'showdown',
'rtx.entry':f=>'entry fee '+f,'rtx.deep':'Deep room','rtx.endless':'Endless pot',
'endless.tier':n=>'Tier '+n,
/* --- reliques --- */
'relic.lunettes.n':'Glasses','relic.lunettes.d':'Permanent relic. Once per hand, reveals the next card in the shoe before you decide to hit.',
'relic.jeton.n':'Cracked Chip','relic.jeton.d':'Permanent relic. If you lose a hand with a total of 20, you get half your bet back.',
'relic.clope.n':'Cigarette','relic.clope.d':'Permanent relic. Your streak builds 30 % faster, all the time.',
'relic.as.n':'Loaded Ace','relic.as.d':'Permanent relic. When you win a hand containing an Ace: +1 to the multiplier.',
'relic.froid.n':'Cool Head','relic.froid.d':'Permanent relic. If you win a hand at streak ≥ 75 %: +1 to the multiplier.',
'relic.compteur.n':'Counter','relic.compteur.d':'Permanent relic. Constantly shows your odds of going over 21 on the next hit.',
'relic.mecene.n':'Patron','relic.mecene.d':'Permanent relic. +4 free at the start of every hand.',
'relic.usurier.n':'Loan Shark','relic.usurier.d':'Permanent relic. At the start of every hand: +1 per 5 in the bank (up to +6).',
'relic.collector.n':'Collector','relic.collector.d':'Permanent relic. Special editions (FOIL/HOLO/POLY) show up 3× more often on your cards.',
'relic.maitresse.n':'Trump Card','relic.maitresse.d':'Permanent relic. Your first card each hand is FOIL: bonus cash when you win.',
'relic.bruleur.n':'Burner','relic.bruleur.d':'Permanent relic. If you win a hand at streak ≥ 50 %: hand payout ×1.5.',
'relic.portebonheur.n':'Lucky Charm','relic.portebonheur.d':'Permanent relic. +1 Tarot token slot (you can hold one more token).',
'relic.diplomate.n':'Diplomat','relic.diplomate.d':'Permanent relic. On a push with the dealer, you get half your bet back.',
'relic.talisman.n':'Talisman','relic.talisman.d':'Rare relic. Once per table, your first lost hand is fully refunded.',
'relic.aimant.n':'Magnet','relic.aimant.d':'Rare relic. +1 for every card you draw.',
'relic.phare.n':'The Lighthouse','relic.phare.d':'Rare relic. CHARLIE (5 cards without busting) pays ×3 instead of ×2.',
/* --- tarots --- */
'tarot.etoile.n':'The Star','tarot.etoile.d':'Play any time: +2 STREAK right away (builds your luck).','tarot.etoile.u':'+2 streak',
'tarot.jugement.n':'Judgement','tarot.jugement.d':'Play any time: jump straight up one STREAK level.','tarot.jugement.u':'STREAK +1 level',
'tarot.soleil.n':'The Sun','tarot.soleil.d':'Adds 18 to your bank right away, any time.','tarot.soleil.u':'+18',
'tarot.diable.n':'The Devil','tarot.diable.d':'Play on your hand: turns one of your cards POLYCHROME, multiplying the hand payout (×1.5).','tarot.diable.u':c=>'Polychrome: '+c,
'tarot.lune.n':'The Moon','tarot.lune.d':'Play on your hand: turns one of your cards HOLOGRAPHIC (+1 to the hand multiplier).','tarot.lune.u':c=>'Holo: '+c,
'tarot.etoileD.n':'The Shooting Star','tarot.etoileD.d':'Play on your hand: turns one of your cards FOIL, paying bonus cash when the hand is won.','tarot.etoileD.u':c=>'Foil: '+c,
'tarot.pendu.n':'The Hanged Man','tarot.pendu.d':'Play during the hand: cancels the last card you drew (saves you when you drew one too many).','tarot.pendu.u':c=>'Removed: '+c,
'tarot.magicien.n':'The Magician','tarot.magicien.d':'Play during the hand: rigs your next draw so it is the best possible card for your hand.','tarot.magicien.u':'Next card rigged',
'tarot.roue.n':'The Wheel','tarot.roue.d':'Play on your hand: a 1-in-2 chance to add a random edition (FOIL, HOLO or POLY) to a card; otherwise nothing.','tarot.roue.u':e=>e+' edition!','tarot.roue.f':'Missed…',
/* --- services --- */
'svc.soin.n':'Cash Advance','svc.soin.d':'Tops your bank up to the table’s recommended bankroll.','svc.soin.u':'Bank topped up',
'svc.assurance.n':'Insurance','svc.assurance.d':'Your next loss on this table is refunded (1×).','svc.assurance.u':'Insured',
'svc.videur.n':'Tip the Bouncer','svc.videur.d':'+1 second-chance token.','svc.videur.u':'+1 second chance',
/* --- déblocages : tournée --- */
'unlock.bank.n':'Nest Egg','unlock.bank.d':n=>'Starting cash +'+(15*(n+1)),
'unlock.pourboire.n':'Tip','unlock.pourboire.d':n=>'+'+(n+1)+' at the start of every hand',
'unlock.net.n':'Safety Net','unlock.net.d':n=>'Starting second chances: '+(3+n+1),
'unlock.tarot.n':'Pocket','unlock.tarot.d':n=>'+1 permanent Tarot slot',
'unlock.contact.n':'Contact','unlock.contact.d':n=>'Start every circuit with a free relic',
'unlock.relic2.n':'Vault','unlock.relic2.d':n=>'Unlocks 3 RARE relics in the shop (Talisman, Magnet, The Lighthouse)',
/* --- déblocages : sans fin --- */
'unlock.bankI.n':'Seed Money','unlock.bankI.d':n=>'Starting pot +'+(15*(n+1)),
'unlock.pourboireI.n':'Annuity','unlock.pourboireI.d':n=>'+'+(n+1)+' every hand, non-stop',
'unlock.plafond.n':'Ceiling','unlock.plafond.d':n=>'Starting bet ceiling +'+(10*(n+1))+' %',
'unlock.elan.n':'Momentum','unlock.elan.d':n=>'Start straight at tier '+(1+(n+1)),
'unlock.cashplus.n':'Launderer','unlock.cashplus.d':n=>'Cashing out the pot pays +'+(25*(n+1))+' %',
'unlock.boon2.n':'Pacts','unlock.boon2.d':n=>'Unlocks 2 RARE tier perks (Boosted Streak, Special Hands ×2)',
/* --- jetons d'effet (uniquement ceux qui portent un mot) --- */
'tok.bank':'+$','tok.pourboire':'+$<small class="sym">/hand</small>','tok.net':'+1 <small>try</small>',
'tok.tarot':'+1 <small>slot</small>','tok.contact':'+1<small>◆</small>','tok.relic2':'+3<small>◆</small>',
'tok.plafond':'+% <small>bet</small>','tok.elan':'+1 <small>tier</small>','tok.cashplus':'+25<small class="sym">%★</small>',
'tok.boon2':'+2 <small>perks</small>',
'tok.lunettes':'PEEK','tok.jeton':'½ <small>BET</small>','tok.compteur':'BUST<small class="sym">%</small>',
'tok.collector':'ED<small>×3</small>','tok.aimant':'+1<small class="sym">$/card</small>',
'tok.talisman':'1 <small>LIFE</small>','tok.etoile':'+2 <small class="sym">streak</small>',
'tok.jugement':'+1<small class="sym">lv</small>','tok.pendu':'−1 <small>card</small>',
'tok.magicien':'IDEAL','tok.roue':'ED<small>?</small>','tok.assurance':'INSU<small>R</small>',
'tok.videur':'+1 <small>try</small>',
/* --- bonus de palier (infini) --- */
'boon.mult.t':'+1 MULT CAP','boon.mult.d':'The multiplier can climb higher.',
'boon.income.t':'+5 / HAND','boon.income.d':'Passive income every hand.',
'boon.betmax.t':'MAX BET +25 %','boon.betmax.d':'Your bet ceiling rises: aim bigger.',
'boon.filet.t':'STREAK NET','boon.filet.d':'On a loss, the STREAK does not drop to zero: it only loses one level.',
'boon.cash.t':'+20 % POT','boon.cash.d':'An immediate injection into your pot.',
'boon.baraplus.t':'BOOSTED STREAK','boon.baraplus.d':'Gutsy plays give +1 extra STREAK.',
'boon.evt3.t':'SPECIAL HANDS ×2','boon.evt3.d':'A special hand every 3 hands (instead of 5).',
/* --- mains spéciales (infini) --- */
'evt.doree.t':'GOLDEN HAND','evt.doree.d':'payouts doubled on this hand',
'evt.forcee.t':'FORCED BET','evt.forcee.d':'max bet required',
'evt.pompette.t':'TIPSY DEALER','evt.pompette.d':'the dealer stands on 16',
'evt.etoile.t':'STARRED CARD','evt.etoile.d':'your first card is HOLO (+1 mult)',
/* --- contrats --- */
'ctr.c5':'win a 5-card hand','ctr.c21':'win with a perfect 21','ctr.cpress':'win at streak ≥ 75 %',
'ctr.cmult':'win a hand at ×3 or more','ctr.cdbl':'win a DOUBLED hand',
'ctr.csuite':'win with a STRAIGHT','ctr.ccoul':'win with a FLUSH',
},
fr:{
'ui.turnsLeft':'TOURS<br>RESTANTS','ui.hand':(a,b)=>'main '+a+'/'+b,
'ui.bet':'MISE','ui.mult':'MULT','ui.gain':'GAIN','ui.potLbl':'CAGNOTTE',
'ui.dealer':'Croupier','ui.you':'Toi','ui.peek':'VOIR','ui.peekTitle':'Lis la prochaine carte du sabot',
'ui.pause':'Pause','ui.lives':'Vies (secondes chances)','ui.streak':'BARAKA',
'ui.lvl':(l,m)=>'· NIV '+l+' ×'+m,'ui.relics':'reliques',
'ui.next':c=>'PROCHAINE : '+c,'ui.bustRisk':p=>'RISQUE DE BUST : '+p+'%',
'menu.sub':'Choisis ton mode de jeu. Chaque mode a <b>sa Planque</b> et sa <b>réputation</b>.',
'menu.circuit':'LA TOURNÉE','menu.circuitSub':n=>n+' tables · une fin · reliques & tarots',
'menu.endless':'SANS FIN','menu.endlessSub':'blackjack pur · monte les paliers',
'menu.recTables':d=>'record '+d+' table'+(d>1?'s':''),'menu.recTier':p=>'record palier '+p,
'planque.title':'LA PLANQUE',
'planque.subCircuit':'Dépense ta <b>réputation</b> en avantages permanents, puis repars pour une nouvelle <b>tournée</b>.',
'planque.subInf':'Améliore ta <b>cagnotte</b> avec ta <b>réputation</b>, puis repars.',
'planque.modeCircuit':'LA TOURNÉE','planque.modeInf':'∞ SANS FIN',
'planque.rep':'réputation','planque.best':'RECORD',
'planque.tables':d=>d+' table'+(d>1?'s':''),'planque.tierN':p=>'palier '+p,
'planque.upgrades':'AMÉLIORATIONS','planque.upgradesSub':'avantages permanents',
'planque.allMax':'tout au max','planque.avail':n=>n+' dispo'+(n>1?'s':''),
'planque.leadCircuit':'Dépense ta <b>réputation</b> en avantages permanents.',
'planque.leadInf':'Renforce ta <b>cagnotte</b> avec ta <b>réputation</b>.',
'planque.back':'DOS DE CARTE','planque.backSub':(i,n)=>'modèle '+i+' / '+n,
'planque.backLead':'Choisis l’habillage du dos de tes cartes.',
'planque.seeAll':'tout voir ▸','planque.menu':'← MENU','planque.start':'COMMENCER',
'planque.startInf':'sans fin · blackjack pur','planque.startResume':n=>'reprise · table '+n,
'planque.startCircuit':n=>'la tournée · '+n+' tables',
'planque.zone2':'ZONE 2','planque.zone2Sub':'raccourci',
'planque.resumeTable':'REPRENDRE À','planque.resumeTier':'REPRENDRE AU',
'planque.tierLabel':n=>'Palier '+n,'planque.tableLabel':n=>'Table '+n,
'planque.max':'MAX','planque.prevBack':'Dos précédent','planque.nextBack':'Dos suivant',
'planque.restartTitle':'Recommencer ce mode (perd la réputation du mode)','planque.rulesTitle':'Règles du jeu',
'set.title':'PARAMÈTRES','set.open':'⚙ PARAMÈTRES','set.lang':'LANGUE','set.close':'FERMER','set.btnTitle':'Paramètres',
/* --- publicité (bouchon de démo) --- */
'ad.tag':'PUB','ad.interTag':'INTERSTITIEL','ad.rewardedTag':'PUB RÉCOMPENSÉE',
'ad.yourAd':'VOTRE PUB ICI','ad.format':'emplacement · 320×480','ad.install':'INSTALLER',
'ad.demoTag':'DÉMO — aucune régie branchée','ad.demoClick':'Pub de démo — rien à cliquer',
'ad.skipIn':n=>'Passer dans '+n+' s','ad.continue':'CONTINUER',
'ad.rewardIn':n=>'Récompense dans '+n+' s','ad.rewardGot':'RÉCOMPENSE OBTENUE','ad.claim':'RÉCUPÉRER',
'ad.aborted':'Récompense non obtenue','ad.demoReward':'Récompense de démo',
'ad.retryBtn':'▶ SECONDE CHANCE','ad.retrySub':n=>'regarde une pub · '+n+' restante'+(n>1?'s':''),
'ad.retryReward':'Rejouer cette table','ad.retryAborted':'Pub interrompue — pas de reprise',
'ad.repBtn':'▶ DOUBLER TA RÉPUTATION','ad.repSub':r=>'+'+r+' en plus','ad.repReward':r=>'+'+r+' de réputation',
'ad.rerollBtn':'▶ GRATUIT','ad.rerollReward':'Une relance de boutique offerte',
'ad.boonBtn':'▶ RELANCER LES BONUS','ad.boonSub':'3 nouvelles options','ad.boonReward':'3 nouveaux bonus',
/* --- paramètres : pub --- */
'set.ads':'PUBLICITÉS (DÉMO)','set.adTestI':'TESTER UN INTERSTITIEL','set.adTestR':'TESTER UNE RÉCOMPENSÉE',
'set.adFree':'SANS PUB','set.adCaps':'IGNORER LES PLAFONDS','set.on':'ACTIVÉ','set.off':'COUPÉ',
'set.adsNote':'Démo uniquement : aucune régie n’est branchée. « Sans pub » simule l’achat (les récompensées restent). « Ignorer les plafonds » déclenche chaque interstitiel pour que tu les voies — coupé, les vraies règles s’appliquent : 1 pub maximum toutes les 3 tables et jamais à moins de 2 min d’intervalle.',

'rules.title':'RÈGLES','rules.close':'FERMER',
'rules.goal':'<span class="rt">BUT</span>Bats le croupier à chaque main sans dépasser <span class="k">21</span>. Une figure vaut 10, l\'As vaut 1 ou 11.',
'rules.table':'<span class="rt">LA TABLE</span>Joue <span class="k">toutes les mains imposées</span>, mise dans la <span class="k">limite</span> (min–max fixe), et atteins l\'<span class="k">objectif de gain</span> avant la dernière main. Sous l\'objectif = table perdue.',
'rules.moves':'<span class="rt">TES COUPS</span><span class="k">TIRER</span> une carte, <span class="k">RESTER</span> sur ta main, ou <span class="k">FORCER LA CHANCE</span> (2 cartes, on garde la meilleure · 1×/table).',
'rules.stars':'<span class="rt"><i class="pxstar"></i> ÉTOILES</span>Chaque table en donne selon ton résultat : <span class="k">objectif</span> · <span class="k">confort</span> · <span class="k">maîtrise</span>. Plus tu en décroches, plus ta <span class="k">réputation</span> grimpe.',
'rules.streak':'<span class="rt">BARAKA</span>Ta barre de <span class="k">veine</span> monte à chaque victoire (<span class="k">coup culotté = +2</span>) et débloque des <span class="k">multiplicateurs</span> de plus en plus forts. Perdre une main la <span class="d">remet à zéro</span>.',
'rules.combos':'<span class="rt">COMBOS</span>Le vrai jeu : <span class="k">construis</span> tes mains, ne te contente pas de battre le croupier.<br><span class="k">21 PARFAIT ×3</span> · <span class="k">CHARLIE</span> (5 cartes) ×2 · <span class="k">COULEUR</span> (3+ même enseigne) ×2 · <span class="k">SUITE</span> (3+ rangs qui se suivent) ×2 · BLACKJACK ×1.5 · PAIRE DE 7 ×1.5 · ARC-EN-CIEL (4 enseignes) ×1.5.<br>Les pastilles sur le tapis montrent ce qui est acquis et à portée.',
'rules.bonus':'<span class="rt">PETITS BONUS</span>Des coups de pouce au multiplicateur selon la situation : <span class="k">COUR</span> (2+ figures) ×1.5 · <span class="k">FILOU</span> (gagner avec ≤15) ×1.5 · <span class="k">AU POIL</span> (battre le croupier d\'un point) ×1.5 · <span class="k">CLUTCH</span> (dernière main) ×1.5 · <span class="k">REMONTADA</span> (parti ≤11, fini ≥17) ×1.3.',
'rules.contracts':'<span class="rt"><i class="pxi pxi-scroll"></i> CONTRATS</span>Chaque table propose un <span class="k">défi optionnel</span> (« gagne une main de 5 cartes »…) qui rapporte des <span class="k">★ bonus</span>. Rempli ou non, la table continue normalement.',
'rules.circuit':'<span class="rt">LA TOURNÉE</span><span class="k">24 tables · 8 zones · un boss tous les 3 niveaux</span>. Après un boss : <span class="k">encaisser</span> ta réputation à La Planque, ou <span class="d">continuer</span> pour plus gros. Atteins la <span class="k">zone 2</span> deux fois pour débloquer le <span class="k">raccourci</span>.',
'rules.hideout':'<span class="rt">LA PLANQUE</span>Dépense ta <span class="k">réputation <i class="pxstar"></i></span> en avantages permanents (reliques, tarots, éditions) avant de repartir.',
'rules.endless':'<span class="rt">SANS FIN</span>Pas d\'objectif : fais grimper ta cagnotte tant que tu peux miser. Chaque <span class="k">palier</span> = un bonus au choix et des mises plus hautes · toutes les 5 mains, une <span class="d">main spéciale</span>. <span class="k">ENCAISSER</span> convertit ta cagnotte en réputation — la <span class="d">banqueroute</span> ne garde que les paliers.',
'upg.title':'AMÉLIORATIONS','backs.title':'DOS DE CARTE',
'rst.title':'RECOMMENCER ?','rst.text':'Êtes-vous sûr de vouloir <b>recommencer la progression de ce mode</b> ?<br>Tu perds la <b>réputation</b>, les <b>déblocages</b> et le <b>record</b> de ce mode uniquement.',
'rst.cancel':'ANNULER','rst.ok':'RECOMMENCER',
'pause.title':'PAUSE','pause.sub':'La partie est en attente.','pause.resume':'REPRENDRE',
'pause.cash':'ENCAISSER','pause.cashSub':'convertit ta cagnotte en réputation',
'pause.rules':'RÈGLES','pause.menu':'RETOUR AU MENU','pause.menuSub':'abandonne la partie · tu encaisses ta réputation',
'pal.title':'PALIER','pal.sub':'Choisis une <b>possibilité</b> pour la suite.',
'pal.cash':r=>'ENCAISSER '+r,'pal.cashSub':'s\'arrêter ici · bonus de palier +20 %',
'shop.title':'TABLE FRANCHIE','shop.titleBoss':'BOSS VAINCU','shop.titleLast':'CASINO DÉVALISÉ',
'shop.sub':(d,b,pot,rew)=>'Table <b>'+d+'</b> tenue · <b>'+b+'</b> en poche · cagnotte <b>'+pot+'</b> <span style="color:var(--muted)">(+'+rew+')</span>',
'shop.total':'total','shop.reroll':c=>'RELANCER ('+c+')',
'shop.cash':'ENCAISSER','shop.finish':'TERMINER','shop.repSuffix':'réput.',
'shop.next':'TABLE SUIVANTE →','shop.nextInfo':(n,goal,cap,fee)=>n+' · obj. '+goal+' · conseillé '+cap+fee,
'shop.fee':f=>' · droit d\'entrée '+f,
'shop.nextObj':(n,goal,cap)=>'PROCHAINE · <b>'+n+'</b> — objectif <b style="color:var(--gold)">'+goal+'</b> · capital conseillé <b>'+cap+'</b>',
'shop.feeObj':f=>' · entrée <b style="color:var(--red)">'+f+'</b>',
'shop.gateFee':f=>'Salle plus exclusive — droit d\'entrée '+f+'.',
'shop.gateDone':'Tu as bouclé la run. Encaisse ta réputation.',
'shop.empty':'Rien à acheter ici.','shop.tagService':'✚ SERVICE','shop.tagTarot':'TAROT','shop.tagRelic':'◆ RELIQUE',
'shop.full':'PLEIN','shop.owned':'ACQUIS',
'insp.tarot':'JETON TAROT · à usage unique','insp.relic':'RELIQUE · effet permanent',
'insp.use':'UTILISER','insp.sell':v=>'VENDRE +'+v,'insp.close':'FERMER','msg.sold':'REVENDU',
'act.bet':'MISER','act.betSub':b=>'mise '+b,'act.betChoose':'choisis ta mise','act.handSuffix':(h,m)=>' · main '+h+'/'+m,
'act.hit':'TIRER','act.hitSub':'+1 carte','act.risk':'RISQUER','act.riskSub':'+bonus si survie',
'act.stand':'RESTER','act.standSub':'garde ta main',
'act.split':'SÉPARER','act.splitSub':'paire · deux mains',
'act.double':'DOUBLER','act.doubleSub':'mise ×2 · une seule carte',
'act.force':'FORCER LA CHANCE','act.forceSub':'garde la meilleure · 1×/table',
'act.forceUsed':'déjà utilisé cette table','act.forceOff':'2 cartes 17-20 · garde la meilleure',
'msg.notNow':'PAS MAINTENANT','msg.notNowSub':'utilisable en jeu',
'msg.noCards':'PAS DE CARTE','msg.cant':'IMPOSSIBLE','msg.keep3':'garde ≥3 cartes',
'msg.slotsFull':'SLOTS PLEINS','msg.relicsFull':'RELIQUES PLEINES','msg.max':n=>n+' max',
'msg.split':'SÉPARÉ','msg.splitSub':c=>c+' · deux mains',
'msg.hand':n=>'MAIN '+n,'msg.handSub':'à toi de jouer',
'msg.doubled':'DOUBLÉ','msg.doubledSub':'mise ×2 · une seule carte',
'msg.forced':'FORCÉ','msg.kept':c=>'gardé '+c,
'msg.insurance':'ASSURANCE','msg.insuranceSub':'perte remboursée',
'msg.talisman':'TALISMAN','msg.talismanSub':'première perte remboursée',
'msg.gutsy':'CULOTTÉ !','msg.gutsySub':n=>'+'+n+' baraka',
'msg.entryFee':'DROIT D\'ENTRÉE','msg.boss':'BOSS','msg.miniboss':'MINI-BOSS',
'msg.zone':(n,name)=>'ZONE '+n+(name?' — '+name:''),
'msg.contract':'CONTRAT REMPLI','msg.income':'REVENU',
'inc.patron':n=>'Mécène +'+n,'inc.shark':n=>'Usurier +'+n,'inc.tip':n=>'Pourboire +'+n,'inc.tier':n=>'Palier +'+n,
'msg.endlessStart':'SANS FIN','msg.endlessStartSub':'monte aussi haut que possible',
'm.blackjack':'BLACKJACK','m.perfect':'21 PARFAIT','m.charlie':'CHARLIE','m.pair7':'PAIRE DE 7',
'm.flush':'COULEUR','m.straight':'SUITE','m.rainbow':'ARC-EN-CIEL','m.pushing':'INSISTANCE',
'm.streak':l=>'BARAKA NIV '+l,'m.burner':'BRÛLEUR','m.foil':'FOIL','m.holo':'HOLO','m.poly':'POLY',
'm.foilV':n=>'+'+n+' jet','m.ace':'AS TRUQUÉ','m.cool':'SANG-FROID',
'm.court':'COUR','m.lowball':'FILOU','m.comeback':'REMONTADA','m.clutch':'CLUTCH','m.byone':'AU POIL',
'm.zonecap':'PLAFOND ZONE','m.golden':'DORÉE',
'ed.card':n=>'CARTE '+n,'ed.foil':'+ argent bonus','ed.holo':'+1 au multiplicateur','ed.poly':'× multiplicateur',
'cb.to21':n=>'21 PARFAIT ×3 · à '+n,'cb.charlie':'CHARLIE ×2 · +1 carte',
'cb.flush':s=>'COULEUR ×2 · +1 '+s,'cb.rainbow':'ARC-EN-CIEL ×1.5 · +1 carte',
'cb.pair7':'PAIRE DE 7 · tire un 7','cb.straight':'SUITE ×2 · possible',
'cb.streak':(l,n)=>'BARAKA NIV '+l+' dans '+n,
'top.mastery':m=>'maîtrise ≥'+m,'top.betRange':(a,b)=>'mise '+a+'–'+b,
'top.stars':n=>n+' étoile'+(n>1?'s':''),'top.pot':p=>'cagnotte '+p,
'top.contractDone':'✓ contrat rempli','top.record':v=>'record '+v,
'top.worth':r=>'vaut '+r+' en pause',
'top.metaCircuit':(z,zn,i,n)=>'zone '+z+' · '+zn+' · '+i+'/'+n,
'top.metaInf':(p,a,b)=>'∞ SANS FIN · palier '+p+' · mise '+a+'–'+b,
'w.jackpot':['JACKPOT!','MÉGA!','BOOM!','EN FEU!'],
'w.win':['GAGNÉ!','OUAIS!','BANG!','CLASSE!','POW!'],
'w.bj':['BLACKJACK!'],'w.push':['ÉGALITÉ','MATCH NUL'],
'w.lose':['RATÉ!','ZUT!','PERDU!','AÏE!'],'w.bust':['BUSTÉ!','CRAMÉ!','TROP HAUT!'],
'w.betBack':'mise rendue',
'sp.win':'GAGNÉ','sp.push':'ÉGALITÉ','sp.lose':'PERDU','sp.hand':i=>'Main '+i+' : ',
'lost.goal':'OBJECTIF MANQUÉ','lost.goalTxt':m=>'Tu finis sous l’objectif de gain de la table — il te manquait <b style="color:var(--red)">'+m+'</b>.',
'lost.broke':'À SEC','lost.brokeTxt':'Plus de quoi miser le minimum de la table.',
'lose.info':(n,pot)=>'Table <b>'+n+'</b> · Cagnotte : <b>'+pot+'</b>',
'lose.retry':'SECONDE CHANCE','lose.tokens':n=>n+' jeton'+(n>1?'s':'')+' restant'+(n>1?'s':''),
'lose.giveup':'ABANDONNER','lose.giveupSub':r=>'encaisse '+r,
'endless.bust':'BANQUEROUTE','endless.bustTxt':'Plus de quoi miser. Ta cagnotte s’arrête ici.',
'end.cash':'TU ENCAISSES','end.circuitOver':'FIN DE LA TOURNÉE','end.potGone':'CAGNOTTE ÉPUISÉE',
'end.cashTxt':'Tu pars avec la cagnotte avant que ça tourne mal.',
'end.halfTxt':'Tu repars quand même avec la moitié de ta cagnotte.',
'end.infCashTxt':b=>'Tu convertis ta cagnotte en réputation'+(b?' — <b style="color:var(--gold)">bonus de palier +20 %</b>':'')+'.',
'end.infStopTxt':'Ta plongée s’arrête.',
'end.missing':(m,prox)=>'<br>Il te manquait <b style="color:var(--red)">'+m+'</b> pour l\'objectif'+(prox?' <span style="color:var(--muted)">— prime de proximité '+prox+'</span>':'')+'.',
'end.infStats':(peak,tier)=>'Cagnotte max : <b style="color:var(--gold)">'+peak+'</b> · Palier atteint : <b>'+tier+'</b>',
'end.stats':(d,b)=>'Tables tenues : <b>'+d+'</b> · Argent : <b>'+b+'</b>',
'end.rep':(g,total)=>'Réputation : <b>'+g+'</b>','end.repTotal':t=>' &nbsp;→&nbsp; total <b>'+t+'</b>',
'end.vault':c=>' <span style="color:var(--muted)">+ coffre '+c+'</span>',
'end.newRecord':'NOUVEAU RECORD !',
'end.recordInf':(tier,peak)=>'Record : palier '+tier+' · '+peak,
'end.recordCircuit':(d,c)=>'Record : '+d+' table'+(d>1?'s':'')+' · '+c,
'end.won':'MAINS GAGNÉES','end.bestGain':'MEILLEUR GAIN','end.bestMult':'MEILLEUR MULT','end.back':'RETOUR À LA PLANQUE',
'rec.banner':'★ NOUVEAU RECORD ★','obj.reached':'OBJECTIF !','obj.validated':'table validée',
'tbl.0':'Arrière-salle','tbl.1':'Table nerveuse','tbl.2':'Le Videur','tbl.3':'Cave humide',
'tbl.4':'Salon rouge','tbl.5':'Le Banquier','tbl.6':'Fosse aux as','tbl.7':'Table maudite','tbl.8':'La Faucheuse',
'tbl.9':'Salon de jade','tbl.10':'Table feutrée','tbl.11':'Le Concierge',
'tbl.12':'Antichambre','tbl.13':'Coffre à secrets','tbl.14':'Le Comptable',
'tbl.15':'Tripot clandestin','tbl.16':'Cave aux rats','tbl.17':'Le Fossoyeur',
'tbl.18':'Loge dorée','tbl.19':'Miroir sans tain','tbl.20':'La Croupière',
'tbl.21':'Suite royale','tbl.22':'Salle des maîtres','tbl.23':'LE PARRAIN',
'zone.1':'Initiation','zone.2':'La Pression','zone.3':'Casino profond','zone.4':'Cercle rouge',
'zone.5':'Chambre forte','zone.6':'Les Bas-fonds','zone.7':'Sphère privée','zone.8':'Le Sommet',
'rule.nervous':'La baraka monte 2× plus vite','rule.mute':'Croupier muet',
'rule.gros':'Le croupier tire jusqu’à 18','rule.depart':'Table déjà chaude (+30 %)','rule.sec':'Égalité = défaite',
'rtx.0':'Initiation','rtx.4':'Salon feutré','rtx.7':'Croupier impitoyable (18)',
'rtx.boss':r=>'BOSS · '+r,'rtx.bossFinal':'BOSS FINAL · égalité = défaite','rtx.bossPlain':'affrontement',
'rtx.entry':f=>'droit d’entrée '+f,'rtx.deep':'Salle profonde','rtx.endless':'Cagnotte sans fin',
'endless.tier':n=>'Palier '+n,
'relic.lunettes.n':'Lunettes','relic.lunettes.d':'Relique permanente. Une fois par main, révèle la prochaine carte du sabot avant de décider de tirer.',
'relic.jeton.n':'Jeton fendu','relic.jeton.d':'Relique permanente. Si tu perds une main avec un total de 20, tu récupères la moitié de ta mise.',
'relic.clope.n':'Cigarette','relic.clope.d':'Relique permanente. Ta baraka monte 30 % plus vite, tout le temps.',
'relic.as.n':'As truqué','relic.as.d':'Relique permanente. Quand tu gagnes une main qui contient un As : +1 au multiplicateur.',
'relic.froid.n':'Sang-froid','relic.froid.d':'Relique permanente. Si tu gagnes une main avec une baraka ≥ 75 % : +1 au multiplicateur.',
'relic.compteur.n':'Compteur','relic.compteur.d':'Relique permanente. Affiche en continu ta probabilité de dépasser 21 au prochain tirage.',
'relic.mecene.n':'Mécène','relic.mecene.d':'Relique permanente. +4 $ offerts au début de chaque main.',
'relic.usurier.n':'Usurier','relic.usurier.d':'Relique permanente. Au début de chaque main : +1 $ par tranche de 5 $ en banque (jusqu’à +6).',
'relic.collector.n':'Collectionneur','relic.collector.d':'Relique permanente. Les éditions spéciales (FOIL/HOLO/POLY) apparaissent 3× plus souvent sur tes cartes.',
'relic.maitresse.n':'Carte maîtresse','relic.maitresse.d':'Relique permanente. Ta 1re carte de chaque main est FOIL : de l’argent bonus quand tu gagnes.',
'relic.bruleur.n':'Brûleur','relic.bruleur.d':'Relique permanente. Si tu gagnes une main avec une baraka ≥ 50 % : gain de la main ×1,5.',
'relic.portebonheur.n':'Porte-bonheur','relic.portebonheur.d':'Relique permanente. +1 emplacement de jeton Tarot (tu peux garder un jeton de plus).',
'relic.diplomate.n':'Diplomate','relic.diplomate.d':'Relique permanente. En cas d’égalité avec le croupier, tu récupères la moitié de ta mise.',
'relic.talisman.n':'Talisman','relic.talisman.d':'Relique rare. Une fois par table, ta première main perdue est intégralement remboursée.',
'relic.aimant.n':'Aimant','relic.aimant.d':'Relique rare. +1 $ à chaque carte que tu tires.',
'relic.phare.n':'Le Phare','relic.phare.d':'Relique rare. CHARLIE (5 cartes sans dépasser) paie ×3 au lieu de ×2.',
'tarot.etoile.n':'L’Étoile','tarot.etoile.d':'À jouer à tout moment : +2 BARAKA tout de suite (fait monter ta veine).','tarot.etoile.u':'+2 baraka',
'tarot.jugement.n':'Le Jugement','tarot.jugement.d':'À jouer à tout moment : monte directement d’un niveau de BARAKA.','tarot.jugement.u':'BARAKA +1 niveau',
'tarot.soleil.n':'Le Soleil','tarot.soleil.d':'Ajoute aussitôt 18 $ à ta banque, à tout moment.','tarot.soleil.u':'+18 $',
'tarot.diable.n':'Le Diable','tarot.diable.d':'À jouer sur ta main : transforme une de tes cartes en POLYCHROME, qui multiplie le gain de la main (×1,5).','tarot.diable.u':c=>'Polychrome : '+c,
'tarot.lune.n':'La Lune','tarot.lune.d':'À jouer sur ta main : transforme une de tes cartes en HOLOGRAPHIQUE (+1 au multiplicateur de la main).','tarot.lune.u':c=>'Holo : '+c,
'tarot.etoileD.n':'L’Étoile filante','tarot.etoileD.d':'À jouer sur ta main : transforme une de tes cartes en FOIL, qui rapporte de l’argent bonus quand la main est gagnée.','tarot.etoileD.u':c=>'Foil : '+c,
'tarot.pendu.n':'Le Pendu','tarot.pendu.d':'À jouer pendant la main : annule ta dernière carte tirée (sauve-toi quand tu as tiré la carte de trop).','tarot.pendu.u':c=>'Retiré : '+c,
'tarot.magicien.n':'Le Magicien','tarot.magicien.d':'À jouer pendant la main : truque ta prochaine carte tirée, qui sera la meilleure possible pour ta main.','tarot.magicien.u':'Prochaine carte truquée',
'tarot.roue.n':'La Roue','tarot.roue.d':'À jouer sur ta main : 1 chance sur 2 d’ajouter une édition aléatoire (FOIL, HOLO ou POLY) à une carte ; sinon, rien.','tarot.roue.u':e=>'Édition '+e+' !','tarot.roue.f':'Raté…',
'svc.soin.n':'Avance de fonds','svc.soin.d':'Renfloue ta banque jusqu’au capital conseillé de la table.','svc.soin.u':'Banque renflouée',
'svc.assurance.n':'Assurance','svc.assurance.d':'Ta prochaine perte de la table est remboursée (1×).','svc.assurance.u':'Assuré',
'svc.videur.n':'Pourboire au videur','svc.videur.d':'+1 jeton de seconde chance.','svc.videur.u':'+1 seconde chance',
'unlock.bank.n':'Pécule','unlock.bank.d':n=>'Argent de départ +'+(15*(n+1))+' $',
'unlock.pourboire.n':'Pourboire','unlock.pourboire.d':n=>'+'+(n+1)+' $ au début de chaque main',
'unlock.net.n':'Filet','unlock.net.d':n=>'Secondes chances de départ : '+(3+n+1),
'unlock.tarot.n':'Poche','unlock.tarot.d':n=>'+1 emplacement Tarot permanent',
'unlock.contact.n':'Contact','unlock.contact.d':n=>'Commence chaque tournée avec une relique offerte',
'unlock.relic2.n':'Coffre','unlock.relic2.d':n=>'Débloque 3 reliques RARES en boutique (Talisman, Aimant, Le Phare)',
'unlock.bankI.n':'Mise de fond','unlock.bankI.d':n=>'Cagnotte de départ +'+(15*(n+1)),
'unlock.pourboireI.n':'Rente','unlock.pourboireI.d':n=>'+'+(n+1)+' $ à chaque main, en continu',
'unlock.plafond.n':'Plafond','unlock.plafond.d':n=>'Plafond de mise de départ +'+(10*(n+1))+' %',
'unlock.elan.n':'Élan','unlock.elan.d':n=>'Démarre directement au palier '+(1+(n+1)),
'unlock.cashplus.n':'Blanchisseur','unlock.cashplus.d':n=>'L’encaissement de la cagnotte rapporte +'+(25*(n+1))+' %',
'unlock.boon2.n':'Pactes','unlock.boon2.d':n=>'Débloque 2 bonus de palier RARES (Baraka dopée, Mains spéciales ×2)',
'tok.bank':'+$','tok.pourboire':'+$<small class="sym">/main</small>','tok.net':'+1 <small>essai</small>',
'tok.tarot':'+1 <small>slot</small>','tok.contact':'+1<small>◆</small>','tok.relic2':'+3<small>◆</small>',
'tok.plafond':'+% <small>mise</small>','tok.elan':'+1 <small>palier</small>','tok.cashplus':'+25<small class="sym">%★</small>',
'tok.boon2':'+2 <small>bonus</small>',
'tok.lunettes':'VOIR','tok.jeton':'½ <small>MISE</small>','tok.compteur':'BUST<small class="sym">%</small>',
'tok.collector':'ÉD<small>×3</small>','tok.aimant':'+1<small class="sym">$/carte</small>',
'tok.talisman':'1 <small>VIE</small>','tok.etoile':'+2 <small class="sym">baraka</small>',
'tok.jugement':'+1<small class="sym">niv</small>','tok.pendu':'−1 <small>carte</small>',
'tok.magicien':'IDÉAL','tok.roue':'ÉD<small>?</small>','tok.assurance':'ASSU<small>R</small>',
'tok.videur':'+1 <small>essai</small>',
'boon.mult.t':'+1 PLAFOND MULT','boon.mult.d':'Le multiplicateur peut monter plus haut.',
'boon.income.t':'+5 $ / MAIN','boon.income.d':'Revenu passif à chaque main.',
'boon.betmax.t':'MISE MAX +25 %','boon.betmax.d':'Ton plafond de mise grimpe : vise plus gros.',
'boon.filet.t':'FILET BARAKA','boon.filet.d':'À la défaite, la BARAKA ne retombe pas à zéro : elle perd juste un niveau.',
'boon.cash.t':'+20 % CAGNOTTE','boon.cash.d':'Injection immédiate dans ta cagnotte.',
'boon.baraplus.t':'BARAKA DOPÉE','boon.baraplus.d':'Les coups culottés donnent +1 BARAKA de plus.',
'boon.evt3.t':'MAINS SPÉCIALES ×2','boon.evt3.d':'Une main spéciale toutes les 3 mains (au lieu de 5).',
'evt.doree.t':'MAIN DORÉE','evt.doree.d':'gains doublés sur cette main',
'evt.forcee.t':'MISE FORCÉE','evt.forcee.d':'mise max obligatoire',
'evt.pompette.t':'CROUPIER POMPETTE','evt.pompette.d':'le croupier s’arrête à 16',
'evt.etoile.t':'CARTE ÉTOILÉE','evt.etoile.d':'ta 1re carte est HOLO (+1 mult)',
'ctr.c5':'gagne une main de 5 cartes','ctr.c21':'gagne avec un 21 parfait','ctr.cpress':'gagne à baraka ≥ 75 %',
'ctr.cmult':'gagne une main à ×3 ou plus','ctr.cdbl':'gagne une main DOUBLÉE',
'ctr.csuite':'gagne avec une SUITE','ctr.ccoul':'gagne avec une COULEUR',
}
};
let LANG=(()=>{try{const v=localStorage.getItem('t21lang');return STR[v]?v:'en';}catch(e){return 'en';}})();
/* t('cle', args…) : chaîne, fonction d'interpolation, ou tableau (mot au hasard) */
function t(key,...args){
  const dict=STR[LANG]||STR.en;
  const v=(key in dict)?dict[key]:STR.en[key];
  if(v===undefined)return key;
  return typeof v==='function'?v(...args):v;
}
function hasStr(key){return (STR[LANG]&&key in STR[LANG])||(key in STR.en);}
