/* No package installation or network access is required. */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const files=['game-data.js','card-art.js','game.js','menu-v2.js','modern-fx.js','controls.js'];
const source=files.map(file=>'\n/* '+file+' */\n'+fs.readFileSync(path.join(root,file),'utf8')).join('\n');
const bundle='/* Generated by node scripts/build.mjs. Edit the source files. */\n(() => {\n'+source+'\n})();\n';
fs.writeFileSync(path.join(root,'cold-deck.js'),bundle);

// Optional self-contained export. A single script preserves all bindings when
// an HTML preview isolates script execution from the global window object.
if(process.argv[2]){
  let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  for(const css of ['modern.css','electric.css']){
    html=html.replace('<link rel="stylesheet" href="'+css+'">',()=>'<style>\n'+fs.readFileSync(path.join(root,css),'utf8')+'\n</style>');
  }
  html=html.replace('<script src="cold-deck.js"></script>',()=>'<script>\n'+bundle.replace(/<\/script/gi,'<\\/script')+'\n</script>');
  html=html.replace(/<link rel="manifest"[^>]+>\s*/,'');
  html=html.replace(/href="(icons\/[^"]+)"/g,(_,file)=>{
    const mime=file.endsWith('.svg')?'image/svg+xml':'image/png';
    return 'href="data:'+mime+';base64,'+fs.readFileSync(path.join(root,file)).toString('base64')+'"';
  });
  const destination=path.resolve(process.argv[2]);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,html);
}
