/* No package installation or network access is required. */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const files=['game-data.js','card-art.js','game.js','menu-v2.js','raster-ui.js','modern-fx.js','controls.js'];
const source=files.map(file=>'\n/* '+file+' */\n'+fs.readFileSync(path.join(root,file),'utf8')).join('\n');
const bundle='/* Generated by node scripts/build.mjs. Edit the source files. */\n(() => {\n'+source+'\n})();\n';
fs.writeFileSync(path.join(root,'cold-deck.js'),bundle);

// Optional self-contained export. A single script preserves all bindings when
// an HTML preview isolates script execution from the global window object.
if(process.argv[2]){
  let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  for(const css of ['modern.css','electric.css','illustrated.css','raster.css','equilibre.css']){
    html=html.replace('<link rel="stylesheet" href="'+css+'">',()=>'<style>\n'+fs.readFileSync(path.join(root,css),'utf8')+'\n</style>');
  }
  // Keep the reading font available in standalone exports as well.
  const copyFont=fs.readFileSync(path.join(root,'fonts/barlow-latin-500-normal.woff2')).toString('base64');
  html=html.replaceAll('url("fonts/barlow-latin-500-normal.woff2")','url("data:font/woff2;base64,'+copyFont+'")');
  const artDir=path.join(root,'assets/illustrations');
  const artData=Object.fromEntries(fs.readdirSync(artDir).filter(file=>file.endsWith('.webp')).map(file=>[file.slice(0,-5),'data:image/webp;base64,'+fs.readFileSync(path.join(artDir,file)).toString('base64')]));
  const portableBundle=bundle.replace('const image=key=>`assets/illustrations/${key}.webp`;',()=>`const illustrationData=${JSON.stringify(artData)}; const image=key=>illustrationData[key];`);
  html=html.replace(/src="assets\/illustrations\/([^"/]+)\.webp"/g,(_,key)=>`src="${artData[key]}"`);
  html=html.replace(/href="assets\/illustrations\/([^"/]+)\.webp"/g,(_,key)=>`href="${artData[key]}"`);
  html=html.replace('<script src="cold-deck.js"></script>',()=>'<script>\n'+portableBundle.replace(/<\/script/gi,'<\\/script')+'\n</script>');
  html=html.replace(/<link rel="manifest"[^>]+>\s*/,'');
  html=html.replace(/(src|href)="(icons\/[^"]+)"/g,(_,attribute,file)=>{
    const mime=file.endsWith('.svg')?'image/svg+xml':'image/png';
    return attribute+'="data:'+mime+';base64,'+fs.readFileSync(path.join(root,file)).toString('base64')+'"';
  });
  const destination=path.resolve(process.argv[2]);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,html);
}
